language: python
python:
- 2.7
env:
  matrix:
    - DOCKER_CONTENT_TRUST=0
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v5_4_0/dockerfiles
- COMPOSE_DOCKER_CLI_BUILD=1 docker build --build-arg WP_VERSION=5.4.0-fpm ./build/wordpress -t trydirect/wordpress:5.4.0-dev --target=dev
- COMPOSE_DOCKER_CLI_BUILD=1 docker build --build-arg WP_VERSION=5.4.0-fpm ./build/wordpress -t trydirect/wordpress:5.4.0-prod --target=prod
- docker-compose up -d
- docker-compose ps
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- cd v5_4_0
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd v5_4_0/dockerfiles
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose images
- docker push trydirect/wordpress:5.4.0-dev
- docker push trydirect/wordpress:5.4.0-prod
- echo "$FRANKFURT_DOCKER_PASS" | docker login "$FRANKFURT_REGISTRY" -u "$FRANKFURT_DOCKER_USER" --password-stdin
- docker push $FRANKFURT_REGISTRYtrydirect/wordpress:5.4.0-dev
- docker push $FRANKFURT_REGISTRYtrydirect/wordpress:5.4.0-prod
